web_student_stage:
    resource: "@webStudentEtudiantBundle/Resources/config/routing.yml"
    prefix:   /

web_student_etudiant:
    resource: "@webStudentEtudiantBundle/Resources/config/routing.yml"
    prefix:   /

