parameters:
#    web_student_user.example.class: webStudent\UserBundle\Example

services:
#    web_student_user.example:
#        class: %web_student_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
