SalutEverybody:
    path:  /affichSalut
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:index }
webStudent_etudiant_homepage:
    pattern:  /salut/{name}
    defaults: { _controller: webStudentEtudiantBundle:Default:index }
accueilAction:
    path: /Accueil/
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:accueil}
layoutAction:
    path: /layout/
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:layout}

#Stage
AjouterStage:
    path: /Stage/ajouterStage
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:ajouterStage}
ModifierStage:
    path: /Stage/modifStage/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:modifierStage}
ConsulterStage:
    path: /Stage/consulterStage/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:consulterStage}
ListeStage:
    path: /Stage/consulterListeStage/
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:listeStage}
#Etudiant
ListeEtudiant:
    path: /Etudiant/listeEtudiant/
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:listeEtudiant}
ConsulterEtudiant:
    path: /Etudiant/consulterEtudiant/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:consulterEtudiant}
ModifierEtudiant:
    path: /Etudiant/modifEtudiant/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:modifierEtudiant}
AjouterEtudiant:
    path: /Etudiant/ajouterEtudiant
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:ajouterEtudiant}
#Entreprise
ListeEntreprise:
    path: /Entreprise/consulterListeEntreprise/
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:listeEntreprise}
ConsulterEntreprise:
    path: /Entreprise/consulterEntreprise/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:consulterEntreprise}
AjouterEntreprise:
    path: /Entreprise/ajouterEntreprise
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:ajouterEntreprise}
ModifierEntreprise:
    path: /Entreprise/modifEntreprise/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:modifierEntreprise}
#Connexion
login:
    pattern:   /login
    defaults:  { _controller: webStudentEtudiantBundle:Etudiant:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
#Compte
ConsulterCompte:
    path: /Compte/consulterCompte/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:consulterCompte }
ModifierCompte:
    path: /Compte/modifierCompte/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:modifierCompte }
#Activite
ListeActivite:
    path: /Activite/consulterListeActivite/
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:listeActivite}