SalutEverybody:
    path:  /affichSalut
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:index }
webStudent_etudiant_homepage:
    pattern:  /salut/{name}
    defaults: { _controller: webStudentEtudiantBundle:Default:index }
accueilAction:
    path: /Accueil/
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:accueil}
layoutAction:
    path: /layout/
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:layout}

#Stage
AjouterStage:
    path: /Etudiant/ajouterStage
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:ajouterStage}
ModifierStage:
    path: /Etudiant/modifStage/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:modifierStage}
ConsulterStage:
    path: /Etudiant/consulterStage/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:consulterStage}
ListeStage:
    path: /Etudiant/consulterListeStage/
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:listeStage}
#Etudiant
ListeEtudiant:
    path: /Etudiant/listeEtudiant/
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:listeEtudiant}
ConsulterEtudiant:
    path: /Etudiant/consulterEtudiant/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:consulterEtudiant}
ModifierEtudiant:
    path: /Etudiant/modifEtudiant/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:modifierEtudiant}
AjouterEtudiant:
    path: /Etudiant/ajouterEtudiant
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:ajouterEtudiant}
#Entreprise
ListeEntreprise:
    path: /Etudiant/consulterListeEntreprise/
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:listeEntreprise}
ConsulterEntreprise:
    path: /Etudiant/consulterEntreprise/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:consulterEntreprise}
AjouterEntreprise:
    path: /Etudiant/ajouterEntreprise
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:ajouterEntreprise}
ModifierEntreprise:
    path: /Etudiant/modifEntreprise/{id}
    defaults: { _controller: webStudentEtudiantBundle:Etudiant:modifierEntreprise}

    fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
 fos_user_profile:
   resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
   prefix: /profile
 
 fos_user_register:
   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
   prefix: /register
 
 fos_user_resetting:
   resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
   prefix: /resetting
 
 fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile